apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: dev-

patchesStrategicMerge:
  - patches/replicas.yaml
  - patches/resources.yaml

configMapGenerator:
  - name: dive25-config
    behavior: merge
    literals:
      - ENVIRONMENT=development
      - DOMAIN=dive25.local
      - LOG_LEVEL=debug
      - CORS_ALLOWED_ORIGINS=https://dev-dive25.local,http://localhost:3000

secretGenerator:
  - name: dive25-secrets
    behavior: merge
    files:
      - mongodb-uri=secrets/mongodb-uri
      - keycloak-client-secret=secrets/keycloak-client-secret
      - jwt-secret=secrets/jwt-secret