services:

  mongodb:
    image: mongo:6.0
    container_name: dive25-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: dive25
    volumes:
      - mongo_data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongodb/mongod.conf:/etc/mongod.conf:ro
    networks:
      - dive25-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # MongoDB Express for MongoDB administration
  mongo-express:
    image: mongo-express:latest
    container_name: dive25-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-admin_password}
    depends_on:
      - mongodb
    networks:
      - dive25-network

  # PostgreSQL for Keycloak
  postgres:
    image: postgres:15
    container_name: dive25-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dive25-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Keycloak Identity Provider
  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: dive25-keycloak
    restart: unless-stopped
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_FEATURES: admin-api,impersonation,import-realm
      # CSP settings - simpler approach
      KC_SPI_CONTENT_SECURITY_POLICY_ENABLED: "true"
      # Let our CSP script handle this dynamically
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: "${DEV_BASE_DOMAIN}"
      KC_HOSTNAME_ADMIN: "${DEV_BASE_DOMAIN}"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_SPI_LOGIN_PROTOCOL_OPENID_CONNECT_SUPPRESS_LOGOUT_CONFIRMATION_SCREEN: "true"
      KC_SPI_EVENTS_LISTENER: "jboss-logging,admin-event-listener"
      KC_HTTP_CORS: "true"
      KC_HTTP_CORS_ALLOWED_ORIGINS: "*"
      KC_HTTP_CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
      KC_HOSTNAME_PORT: "${DEV_KEYCLOAK_PORT}"
      KC_HOSTNAME_PORT_HTTPS: "${DEV_KEYCLOAK_PORT}"
      KC_SPI_LOGIN_PROTOCOL_OPENID_CONNECT_OVERRIDE_WELL_KNOWN: "true"
      KC_SPI_HOSTNAME_DEFAULT_FRONTEND_URL: "${PUBLIC_KEYCLOAK_URL}"
      KC_SPI_LOGIN_PROTOCOL_OPENID_CONNECT_LEGACY_LOGOUT_REDIRECT_URI: "true"
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "${DEV_KEYCLOAK_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dive25-network
    healthcheck:
      test: ["CMD", "/opt/keycloak/bin/kc.sh", "show-config"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Keycloak Configuration
  keycloak-config:
    image: curlimages/curl:latest
    container_name: dive25-keycloak-config
    depends_on:
      keycloak:
        condition: service_healthy
    volumes:
      - ./keycloak/configure-keycloak.sh:/configure-keycloak.sh:ro
      - ./keycloak/realm-export.json:/realm-export.json:ro
      - ./keycloak/identity-providers:/identity-providers:ro
      - ./keycloak/test-users:/test-users:ro
      - ./keycloak/clients:/clients:ro
    environment:
      - KEYCLOAK_URL=${INTERNAL_KEYCLOAK_URL}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - PUBLIC_KEYCLOAK_URL=${PUBLIC_KEYCLOAK_URL}
      - PUBLIC_FRONTEND_URL=${PUBLIC_FRONTEND_URL}
      - PUBLIC_API_URL=${PUBLIC_API_URL}
    entrypoint: ["/bin/sh", "/configure-keycloak.sh"]
    networks:
      - dive25-network

  # Keycloak CSP Configuration
  keycloak-csp:
    image: curlimages/curl:latest
    container_name: dive25-keycloak-csp
    depends_on:
      keycloak-config:
        condition: service_completed_successfully
    volumes:
      - ./keycloak/configure-csp.sh:/configure-csp.sh:ro
    environment:
      - KEYCLOAK_URL=${INTERNAL_KEYCLOAK_URL}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    entrypoint: ["/bin/sh", "/configure-csp.sh"]
    networks:
      - dive25-network

  # OpenLDAP Directory Service
  openldap:
    image: osixia/openldap:latest
    container_name: dive25-openldap
    restart: unless-stopped
    environment:
      LDAP_ORGANISATION: "DIVE25"
      LDAP_DOMAIN: "dive25.local"
      LDAP_BASE_DN: "dc=dive25,dc=local"
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-admin_password}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD:-config_password}
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: ${LDAP_READONLY_PASSWORD:-readonly_password}
      LDAP_TLS: "false"
      LDAP_SKIP_DEFAULT_BOOTSTRAP: "false"
      LDAP_REPLICATION: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./openldap/bootstrap:/container/service/slapd/assets/config/bootstrap
    ports:
      - "389:389"
      - "636:636"
    networks:
      - dive25-network
    healthcheck:
      test: ["CMD", "ldapsearch", "-x", "-H", "ldap://localhost:389", "-D", "cn=admin,dc=dive25,dc=local", "-w", "${LDAP_ADMIN_PASSWORD:-admin_password}", "-b", "dc=dive25,dc=local"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # LDAP Admin UI
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: dive25-phpldapadmin
    restart: unless-stopped
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8085:80"
    depends_on:
      - openldap
    networks:
      - dive25-network

  # OPA Policy Agent
  opa:
    build:
      context: ./opa
      dockerfile: Dockerfile
    container_name: dive25-opa
    restart: unless-stopped
    volumes:
      - ./opa/policies:/opt/opa/policies:ro
      - opa_data:/data
    ports:
      - "8181:8181"
    networks:
      - dive25-network
    healthcheck:
      test: ["CMD", "/opa", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Kong PostgreSQL Database
  kong-database:
    image: postgres:13
    container_name: dive25-kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong_password
    volumes:
      - kong_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped
    networks:
      - dive25-network

  # Kong Migrations
  kong-migrations:
    build:
      context: ./kong
      dockerfile: Dockerfile
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
      # Add environment variables for configuration template
      BASE_DOMAIN: ${BASE_DOMAIN:-dive25.local}
      INTERNAL_FRONTEND_URL: http://dive25-frontend:3000
      INTERNAL_API_URL: http://dive25-api:3000
      INTERNAL_KEYCLOAK_URL: http://dive25-keycloak:8080
      PUBLIC_KEYCLOAK_URL: ${PUBLIC_KEYCLOAK_URL}
    networks:
      - dive25-network
    restart: on-failure

  # Kong API Gateway
  kong:
    build:
      context: ./kong
      dockerfile: Dockerfile
    container_name: dive25-kong
    depends_on:
      - kong-database
      - kong-migrations
      - keycloak
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      # Add environment variables for configuration template
      BASE_DOMAIN: ${BASE_DOMAIN:-dive25.local}
      INTERNAL_FRONTEND_URL: http://dive25-frontend:3000
      INTERNAL_API_URL: http://dive25-api:3000
      INTERNAL_KEYCLOAK_URL: http://dive25-keycloak:8080
      PUBLIC_KEYCLOAK_URL: ${PUBLIC_KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-dive25}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID_FRONTEND:-dive25-frontend}
      KEYCLOAK_CLIENT_ID_API: ${KEYCLOAK_CLIENT_ID_API:-dive25-api}
      SESSION_SECRET: ${SESSION_SECRET:-your_session_secret}
      # Additional configuration
      KONG_PLUGINS: bundled,ldap-auth,oidc-auth
      KONG_SSL_CERT: /etc/kong/certs/dive25-cert.pem
      KONG_SSL_CERT_KEY: /etc/kong/certs/dive25-key.pem
      KONG_NGINX_HTTP_RESOLVER: 1.1.1.1 8.8.8.8
      KONG_NGINX_HTTP_LUA_SHARED_DICT: sessions 10m
      KONG_MEM_CACHE_SIZE: 128m
      KONG_NGINX_WORKER_PROCESSES: 2
      KONG_LOG_LEVEL: debug
    volumes:
      - ./certs:/etc/kong/certs:ro
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped
    networks:
      - dive25-network

  # Optional: Kong Admin UI (can be disabled in production)
  konga:
    image: pantsel/konga:latest
    container_name: dive25-konga
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_PORT: 5432
      DB_USER: kong
      DB_PASSWORD: kong_password
      DB_DATABASE: konga
      NODE_ENV: production
    ports:
      - "1337:1337"
    depends_on:
      - kong-database
      - kong
    networks:
      - dive25-network
    restart: unless-stopped

  # Kong Configuration (combined LDAP and OIDC)
  kong-config:
    build:
      context: ./kong
      dockerfile: Dockerfile.config
    container_name: dive25-kong-config
    restart: on-failure
    depends_on:
      kong:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      openldap:
        condition: service_healthy
    environment:
      KONG_SSL_CERT: /etc/kong/certs/dive25-cert.pem
      KONG_SSL_CERT_KEY: /etc/kong/certs/dive25-key.pem
      KONG_ADMIN_URL: http://kong:8001
      INTERNAL_KEYCLOAK_URL: http://keycloak:8080
      PUBLIC_KEYCLOAK_URL: ${PUBLIC_KEYCLOAK_URL}
      PUBLIC_FRONTEND_URL: ${PUBLIC_FRONTEND_URL}
      PUBLIC_API_URL: ${PUBLIC_API_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-dive25}
      KEYCLOAK_CLIENT_ID_FRONTEND: ${KEYCLOAK_CLIENT_ID_FRONTEND:-dive25-frontend}
      KEYCLOAK_CLIENT_ID_API: ${KEYCLOAK_CLIENT_ID_API:-dive25-api}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET:-change-me-in-production}
      LDAP_HOST: openldap
      LDAP_PORT: 389
      LDAP_BASE_DN: dc=dive25,dc=local
      LDAP_ADMIN_USER: cn=admin,dc=dive25,dc=local
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-admin_password}
    volumes:
      - ./kong/certs:/etc/kong/certs:ro
      - ./.env:/app/.env
      - ./kong/configure-ldap.sh:/app/configure-ldap.sh:ro
      - ./kong/kong.ldap.yml:/app/kong.ldap.yml:ro
      - ./kong/configure-oidc.sh:/app/configure-oidc.sh:ro
    networks:
      - dive25-network

  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: dive25-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - dive25-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Grafana for Visualization
  grafana:
    image: grafana/grafana:latest
    container_name: dive25-grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_ROOT_URL: "https://grafana.dive25.local"
      GF_AUTH_PROXY_ENABLED: "true"
      GF_AUTH_PROXY_HEADER_NAME: "X-WEBAUTH-USER"
      GF_AUTH_PROXY_HEADER_PROPERTY: "username"
      GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/etc/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
    ports:
      - "3100:3000"
    depends_on:
      - prometheus
    networks:
      - dive25-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # MongoDB Exporter for Prometheus
  mongodb-exporter:
    image: percona/mongodb_exporter:0.32.0
    container_name: dive25-mongodb-exporter
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/admin?directConnection=true
    ports:
      - "9216:9216"
    depends_on:
      - mongodb
    networks:
      - dive25-network

  # Node Exporter for Host Metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: dive25-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - dive25-network

  # Backend API
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: dive25-api
    restart: unless-stopped
    environment:
      NODE_ENV: ${ENVIRONMENT}
      PORT: 3000
      MONGODB_URI: mongodb://${MONGO_APP_USERNAME}:${MONGO_APP_PASSWORD}@mongodb:27017/dive25
      KEYCLOAK_AUTH_SERVER_URL: ${INTERNAL_KEYCLOAK_URL}/auth
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID_API}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      PUBLIC_KEYCLOAK_URL: ${PUBLIC_KEYCLOAK_URL}
      OPA_URL: http://opa:8181/v1/data
      OPA_POLICY_PATH: dive25/document_access/allow
      LDAP_URL: ldap://openldap:389
      LDAP_BIND_DN: ${LDAP_BIND_DN:-cn=admin,dc=dive25,dc=local}
      LDAP_BIND_CREDENTIALS: ${LDAP_ADMIN_PASSWORD:-admin_password}
      LDAP_SEARCH_BASE: ${LDAP_SEARCH_BASE:-dc=dive25,dc=local}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      PUBLIC_API_URL: ${PUBLIC_API_URL}
      PUBLIC_FRONTEND_URL: ${PUBLIC_FRONTEND_URL}
      STORAGE_PATH: /app/storage
      TEMP_STORAGE_PATH: /app/temp
      JWT_SECRET: ${JWT_SECRET:-change-me-in-production}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    volumes:
      - api_storage:/app/storage
      - api_temp:/app/temp
      - api_logs:/app/logs
    ports:
      - "${DEV_API_PORT}:3000"
    depends_on:
      - mongodb
      - keycloak
      - opa
      - openldap
    networks:
      - dive25-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/metrics', res => res.statusCode === 200 ? process.exit(0) : process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${PUBLIC_API_URL}/api/v1
        NEXT_PUBLIC_KEYCLOAK_URL: ${PUBLIC_KEYCLOAK_URL}/auth
        NEXT_PUBLIC_KEYCLOAK_REALM: ${KEYCLOAK_REALM}
        NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID_FRONTEND}
        NEXT_PUBLIC_FRONTEND_URL: ${PUBLIC_FRONTEND_URL}
    container_name: dive25-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: ${ENVIRONMENT}
      NEXT_PUBLIC_API_URL: ${PUBLIC_API_URL}/api/v1
      NEXT_PUBLIC_KEYCLOAK_URL: ${PUBLIC_KEYCLOAK_URL}/auth
      NEXT_PUBLIC_KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID_FRONTEND}
      NEXT_PUBLIC_FRONTEND_URL: ${PUBLIC_FRONTEND_URL}
    ports:
      - "${DEV_FRONTEND_PORT}:3000"
    depends_on:
      - api
      - keycloak
    networks:
      - dive25-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  dive25-network:
    driver: bridge

volumes:
  mongo_data:
  postgres_data:
  ldap_data:
  ldap_config:
  prometheus_data:
  grafana_data:
  keycloak_data:
  api_storage:
  api_temp:
  api_logs:
  opa_data:
  kong_data:
