version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: dive25_test
    ports:
      - "27017:27017"
    volumes:
      - mongodb_test_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  ldap:
    image: osixia/openldap:latest
    environment:
      LDAP_ORGANISATION: "DIVE25"
      LDAP_DOMAIN: "dive25.local"
      LDAP_ADMIN_PASSWORD: "admin_password"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_test_data:/var/lib/ldap
      - ldap_test_config:/etc/ldap/slapd.d
    healthcheck:
      test: ["CMD", "ldapsearch", "-x", "-h", "localhost", "-b", "dc=dive25,dc=local", "-D", "cn=admin,dc=dive25,dc=local", "-w", "admin_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_test_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_test_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.test
    environment:
      NODE_ENV: test
      PORT: 3000
      MONGODB_URI: mongodb://admin:admin_password@mongodb:27017/dive25_test?authSource=admin
      LDAP_URL: ldap://ldap:389
      LDAP_BIND_DN: cn=admin,dc=dive25,dc=local
      LDAP_BIND_CREDENTIALS: admin_password
      LDAP_SEARCH_BASE: dc=dive25,dc=local
      ELASTICSEARCH_NODE: http://elasticsearch:9200
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: minio_admin
      MINIO_SECRET_KEY: minio_password
      MINIO_BUCKET: dive25-test-bucket
      JWT_SECRET: test_jwt_secret_key
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
      ldap:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    environment:
      NODE_ENV: test
      PORT: 8080
      API_URL: http://api:3000
    ports:
      - "8080:8080"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mongodb_test_data:
  ldap_test_data:
  ldap_test_config:
  elasticsearch_test_data:
  minio_test_data: 