_format_version: "2.1"
_transform: true

plugins:
  - name: oidc
    service: api-service
    config:
      client_id: dive25-frontend
      client_secret: staging-secret-key
      discovery: https://keycloak.dive25.local/realms/dive25/.well-known/openid-configuration
      introspection_endpoint: https://keycloak.dive25.local/realms/dive25/protocol/openid-connect/token/introspect
      bearer_only: "yes"
      bearer_jwt_auth_enable: "yes"
      bearer_jwt_auth_allowed_auds:
        - dive25-frontend
      ssl_verify: "no"
      token_endpoint_auth_method: client_secret_post
      filters: null
      logout_path: /logout
      redirect_uri_path: /callback
      response_type: code
      recover_page_uri: /recover
      scope: openid
      session_secret: lZbO4EvCWLVTjXJwxbmkR3utCBtl45pxZRE4tFWCBrg=
    enabled: true
