# openldap/docker-compose.yml
version: '3.8'

services:
  openldap:
    image: osixia/openldap:latest
    container_name: dive25-openldap
    hostname: openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_ORGANISATION: "DIVE25"
      LDAP_DOMAIN: "dive25.local"
      LDAP_BASE_DN: "dc=dive25,dc=local"
      LDAP_ADMIN_PASSWORD: "admin_password"
      LDAP_CONFIG_PASSWORD: "config_password"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly_password"
      LDAP_TLS_CRT_FILENAME: "server.crt"
      LDAP_TLS_KEY_FILENAME: "server.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_VERIFY_CLIENT: "try"
    volumes:
      - openldap_data:/var/lib/ldap
      - openldap_config:/etc/ldap/slapd.d
      - ./certs:/container/service/slapd/assets/certs
      - ./bootstrap:/container/service/slapd/assets/config/bootstrap
    command: ["--copy-service"]
    networks:
      - dive25-network

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: dive25-phpldapadmin
    hostname: phpldapadmin
    ports:
      - "8085:80"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - openldap
    networks:
      - dive25-network

volumes:
  openldap_data:
  openldap_config:

networks:
  dive25-network:
    external: true
