# openldap/docker-compose.yml
version: '3.8'

services:
  # OpenLDAP Directory Service
  openldap:
    image: osixia/openldap:latest
    container_name: dive25-openldap
    restart: unless-stopped
    environment:
      LDAP_ORGANISATION: "DIVE25"
      LDAP_DOMAIN: "dive25.local"
      LDAP_BASE_DN: "dc=dive25,dc=local"
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-admin_password}
      LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD:-config_password}
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: ${LDAP_READONLY_PASSWORD:-readonly_password}
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "server.crt"
      LDAP_TLS_KEY_FILENAME: "server.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_VERIFY_CLIENT: "try"
      LDAP_SKIP_DEFAULT_BOOTSTRAP: "false"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./bootstrap:/container/service/slapd/assets/config/bootstrap
      - ./certs/server.crt:/container/service/slapd/assets/certs/server.crt:ro
      - ./certs/server.key:/container/service/slapd/assets/certs/server.key:ro
      - ./certs/ca.crt:/container/service/slapd/assets/certs/ca.crt:ro
    ports:
      - "389:389"
      - "636:636"
    networks:
      - dive25-network
    healthcheck:
      test: ["CMD", "ldapsearch", "-x", "-H", "ldap://localhost:389", "-D", "cn=admin,dc=dive25,dc=local", "-w", "${LDAP_ADMIN_PASSWORD:-admin_password}", "-b", "dc=dive25,dc=local"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # LDAP Admin UI
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: dive25-phpldapadmin
    restart: unless-stopped
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8085:80"
    depends_on:
      - openldap
    networks:
      - dive25-network

volumes:
  ldap_data:
  ldap_config:

networks:
  dive25-network:
    external: true
