# opa/config.yaml
services:
  - name: decision_log
    url: http://prometheus:9090/api/v1/write

bundles:
  authz:
    service: bundle_service
    resource: bundles/dive25-policies
    persist: true
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20

decision_logs:
  service: decision_log
  reporting:
    min_delay_seconds: 30
    max_delay_seconds: 60

persistence_directory: /var/lib/opa

labels:
  app: dive25-opa
  region: dive25
