# opa/docker-compose.yml

services:
  opa:
    image: openpolicyagent/opa:latest
    container_name: dive25-opa
    ports:
      - "8181:8181"
    volumes:
      - ./policies:/opt/opa/policies
      - ./data:/data
      - ./config.yaml:/opt/opa/config.yaml
      - ./plugins:/opt/opa/plugins
    environment:
      - OPA_API_TOKEN=${OPA_API_TOKEN:-system-token}
      - API_URL=${API_URL:-http://dive25-api:3000}
      - FRONTEND_URL=${FRONTEND_URL:-http://frontend:3000}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      - REQUIRE_AUTH=${REQUIRE_AUTH:-false}
      - OPA_ADMIN_TOKEN=${OPA_ADMIN_TOKEN:-admin-token}
    command: ["run", "--server", "--config-file=/opt/opa/config.yaml"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - dive25-network
    restart: unless-stopped
    depends_on:
      - opa-bundle-builder

  opa-bundle-builder:
    image: node:16-alpine
    container_name: dive25-opa-bundle-builder
    volumes:
      - ./policies:/app/policies
      - ./data:/app/data
      - ./bundles:/app/bundles
      - ../api/public/opa/bundles:/app/api-bundles
    working_dir: /app
    environment:
      - BUNDLE_VERSION=${BUNDLE_VERSION:-1.0.0}
      - BUNDLE_KEYID=${BUNDLE_KEYID:-global_key}
      - BUNDLE_SCOPE=${BUNDLE_SCOPE:-dive25}
      - API_SERVER_PATH=/app/api-bundles
    command: >
      sh -c "cd bundles && 
             if [ ! -f create-bundle.js ]; then echo 'Bundle script not found!'; exit 1; fi && 
             node create-bundle.js && 
             cp dive25-bundle.tar.gz /app/api-bundles/dive25-bundle.tar.gz && 
             echo 'Bundle created and copied to API' &&
             tail -f /dev/null"
    networks:
      - dive25-network

networks:
  dive25-network:
    external: true