{
 "title": "Application Logs",
 "tags": [ "logs" ],
 "refresh": "10s",
 "panels": [
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=~\"docker|dive_application\"}"
    }
   ]
  },
  {
   "title": "API Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{filename=~\".*5b818d4.*\"}"
    }
   ]
  },
  {
   "title": "Frontend Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{filename=~\".*9132280a8c04.*\"}"
    }
   ]
  },
  {
   "title": "Application Logs by Level",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"dive_application\"} | json | level=~\"info|warn|error\""
    }
   ]
  },
  {
   "title": "Kong Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{service=\"kong\"}"
    }
   ]
  },
  {
   "title": "Keycloak Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{service=\"keycloak\"}"
    }
   ]
  }
 ]
}