# kong/docker-compose.yml

services:
  kong-database:
    image: postgres:13
    container_name: dive25-kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong_password
    volumes:
      - kong_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped
    networks:
      - dive25-network

  kong-migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
      # Add environment variables for configuration template
      BASE_DOMAIN: dive25.local
      INTERNAL_FRONTEND_URL: http://dive25-frontend:3000
      INTERNAL_API_URL: http://dive25-backend:8000
      INTERNAL_KEYCLOAK_URL: http://dive25-keycloak:8080
      PUBLIC_KEYCLOAK_URL: https://keycloak.dive25.local
    networks:
      - dive25-network
    restart: on-failure

  kong:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dive25-kong
    depends_on:
      - kong-database
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong_password
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      # Add environment variables for configuration template
      BASE_DOMAIN: dive25.local
      INTERNAL_FRONTEND_URL: http://dive25-frontend:3000
      INTERNAL_API_URL: http://dive25-backend:8000
      INTERNAL_KEYCLOAK_URL: http://dive25-keycloak:8080
      PUBLIC_KEYCLOAK_URL: https://keycloak.dive25.local
      KEYCLOAK_REALM: dive25
      KEYCLOAK_CLIENT_ID: dive25-frontend
      KEYCLOAK_CLIENT_ID_API: dive25-api
      SESSION_SECRET: your_session_secret
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped
    networks:
      - dive25-network

  konga:
    image: pantsel/konga:latest
    container_name: dive25-konga
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_PORT: 5432
      DB_USER: kong
      DB_PASSWORD: kong_password
      DB_DATABASE: konga
      NODE_ENV: production
    ports:
      - "1337:1337"
    depends_on:
      - kong-database
    networks:
      - dive25-network
    restart: unless-stopped

volumes:
  kong_data:

networks:
  dive25-network:
    external: true
