server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
  
  - job_name: api_frontend_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: dive_application
          __path__: /var/lib/docker/containers/*5b818d4817fc*/*.log
      - targets:
          - localhost
        labels:
          job: dive_application
          __path__: /var/lib/docker/containers/*9132280a8c04*/*.log
    pipeline_stages:
      - json:
          expressions:
            log: log
            stream: stream
            time: time
      - labels:
          stream:
      - json:
          expressions:
            level: log.level
            message: log.msg
          source: log 