# DIVE25 Base Configuration
# Common settings across all environments

# Project Settings
# DIVE25 Development Environment Configuration
project:
  name: dive25
  container_prefix: dive25
# Database Credentials
databases:
  mongodb:
    root_username: admin
    root_password: admin_password
    app_username: dive25_app
    app_password: app_password
  postgres:
    username: keycloak
    password: keycloak
    database: keycloak
  kong_db:
    username: kong
    password: kong_password
    database: kong
# Authentication Settings
auth:
  keycloak:
    admin_username: admin
    admin_password: admin
    realm: dive25
    client_id_frontend: dive25-frontend
    client_id_api: dive25-api
    client_secret: change-me-in-production
    auth_path: /auth
  jwt:
    secret: change-me-in-production
  session:
    secret: your_session_secret
# LDAP Configuration
ldap:
  admin_password: admin_password
  config_password: config_password
  readonly_password: readonly_password
  bind_dn: cn=admin,dc=dive25,dc=local
  search_base: dc=dive25,dc=local
  domain: dive25.local
  organisation: DIVE25
# Admin Tool Credentials
admin:
  grafana:
    username: admin
    password: admin
  mongodb_express:
    username: admin
    password: admin_password
# Internal Port Assignments (used within containers)
internal_ports:
  # Application Services (3000-3999)
  frontend: 3000
  api: 3000
  # Infrastructure Services (8000-8999)
  keycloak: 8080
  keycloak_https: 8443
  kong_proxy: 8000
  kong_proxy_https: 8443
  kong_admin: 8001
  kong_admin_https: 8444
  opa: 8181
  # Database Services (5000-5999)
  mongodb: 27017
  postgres: 5432
  # Admin/Monitoring Services (9000-9999)
  grafana: 3000
  prometheus: 9090
  phpldapadmin: 80
  konga: 1337
  mongodb_exporter: 9216
  node_exporter: 9100
# Service Names (for internal container communication)
services:
  frontend: frontend
  api: api
  keycloak: keycloak
  kong: kong
  mongodb: mongodb
  postgres: postgres
  opa: opa
  openldap: openldap
  grafana: grafana
  prometheus: prometheus
  phpldapadmin: phpldapadmin
  mongodb_exporter: mongodb-exporter
  node_exporter: node-exporter
  kong_database: kong-database
  konga: konga
# Network Configuration
networks:
  public:
    name: dive25-public
    subnet: 172.30.0.0/24
  service:
    name: dive25-service
    subnet: 172.30.1.0/24
  data:
    name: dive25-data
    subnet: 172.30.2.0/24
  admin:
    name: dive25-admin
    subnet: 172.30.3.0/24
# Logging Configuration (more verbose for development)
logging:
  level: debug
# Security Headers Configuration
security:
  headers:
    keycloak:
      # Fix for CSP header issues
      skip_csp: false
      add:
        - "Strict-Transport-Security:max-age=31536000; includeSubDomains"
        - "X-XSS-Protection:1; mode=block"
        - "X-Content-Type-Options:nosniff"
        - "X-Frame-Options:SAMEORIGIN"
        - "Content-Security-Policy:frame-ancestors 'self'; frame-src 'self'; object-src 'none'; base-uri 'self'; default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:"
    global:
      add:
        - "X-Frame-Options:SAMEORIGIN"
        - "X-XSS-Protection:1; mode=block"
        - "X-Content-Type-Options:nosniff"
        - "Referrer-Policy:strict-origin-when-cross-origin"
        - "Content-Security-Policy:frame-ancestors 'self'; frame-src 'self'; object-src 'none'"
# CORS Configuration
cors:
  allowed_origins:
    - http://localhost:3001
    - http://localhost:3002
    - http://localhost:8080
    - http://localhost:8000
    - http://frontend.localhost:3001
    - http://api.localhost:3002
    - http://keycloak.localhost:8080
# API configuration
api:
  url: https://api.dive25.local:8443
  internal_url: http://api:8080
  version: v1
# Frontend configuration
frontend:
  url: https://frontend.dive25.local:8443
  internal_url: http://frontend:3000
# Environment Settings
environment: development
base_domain: localhost
use_https: false
protocol: http
# Domain Settings (subdomains for each service)
domains:
  frontend: frontend
  api: api
  keycloak: keycloak
  kong: kong
  grafana: grafana
  mongodb_express: mongo-express
  phpldapadmin: phpldapadmin
  prometheus: prometheus
  opa: opa
  konga: konga
  mongodb_exporter: mongodb-exporter
  node_exporter: node-exporter
# External Ports (exposed to host machine)
# Development uses different ports to avoid conflicts with other services
external_ports:
  frontend: 3001
  api: 3002
  keycloak: 8080
  kong_proxy: 8000
  kong_proxy_https: 8443
  kong_admin: 8001
  kong_admin_https: 8444
  grafana: 3100
  mongodb_express: 8081
  phpldapadmin: 8082
  prometheus: 9090
  opa: 8181
  konga: 1337
  mongodb_exporter: 9216
  node_exporter: 9100
# SSL/TLS Configuration (for development - self-signed)
ssl:
  cert_path: ./certs/dev-cert.pem
  key_path: ./certs/dev-key.pem
# Rate Limiting (more permissive for development)
rate_limits:
  per_minute: 300
  per_hour: 15000
