apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mongodb/
  - keycloak/
  - openldap/
  - opa/
  - kong/
  - api/
  - frontend/
  - prometheus/
  - grafana/

commonLabels:
  app.kubernetes.io/part-of: dive25