# mongodb/kubernetes/backup-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: dive25-mongodb
spec:
  schedule: "0 1 * * *"  # Run at 1:00 AM daily
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-backup
            image: mongo:6.0
            command:
            - /bin/bash
            - -c
            - |
              set -e
              TIMESTAMP=$(date +%Y%m%d_%H%M%S)
              BACKUP_DIR="/backup"
              
              echo "Starting MongoDB backup at $(date)"
              
              # Create backup using mongodump
              mongodump \
                --host=mongodb-0.mongodb-headless.dive25-mongodb.svc.cluster.local:27017,mongodb-1.mongodb-headless.dive25-mongodb.svc.cluster.local:27017,mongodb-2.mongodb-headless.dive25-mongodb.svc.cluster.local:27017 \
                --username=$MONGODB_BACKUP_USER \
                --password=$MONGODB_BACKUP_PASSWORD \
                --authenticationDatabase=admin \
                --db=dive25 \
                --gzip \
                --out="${BACKUP_DIR}/backup_${TIMESTAMP}"
              
              # Create archive
              tar -czf "${BACKUP_DIR}/dive25_backup_${TIMESTAMP}.tar.gz" "${BACKUP_DIR}/backup_${TIMESTAMP}"
              
              # Cleanup uncompressed backup
              rm -rf "${BACKUP_DIR}/backup_${TIMESTAMP}"
              
              # Keep only the last 7 backups
              ls -t ${BACKUP_DIR}/dive25_backup_*.tar.gz | tail -n +8 | xargs rm -f
              
              echo "MongoDB backup completed at $(date)"
            env:
            - name: MONGODB_BACKUP_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-username
            - name: MONGODB_BACKUP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-password
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: mongodb-backup-pvc