# mongodb/kubernetes/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: dive25-mongodb
type: Opaque
data:
  mongodb-root-password: BASE64_ENCODED_ROOT_PASSWORD
  mongodb-replica-set-key: BASE64_ENCODED_REPLICA_SET_KEY
  mongodb-app-password: BASE64_ENCODED_APP_PASSWORD
  mongodb-admin-password: BASE64_ENCODED_ADMIN_PASSWORD
  mongodb-readonly-password: BASE64_ENCODED_READONLY_PASSWORD